### ISSUE TITLE
non-ASCII characters break ansible-lint-junit

### ISSUE THREAD

**Issue by gtirloni** [wasilak/ansible-lint-junit#14]
Here's the offending [Ansible task](https://github.com/elastic/ansible-elasticsearch/blob/main/tasks/elasticsearch-template.yml#L3-L9):

```
- name: ensure templates dir is created
  file:
    path: "{{�| es_conf_dir�| }}/templates"
    state: directory
    owner: root
    group: "{{ es_group }}"
    mode: "2750"
```

And here's the output from ansible-lint, which includes the non-ASCII characters:

```
roles/es/tasks/elasticsearch-template.yml:3: var-spacing Variables should have spaces before and after: {{�| es_conf_dir�| }}/templates
```

And the output from ansible-lint-junit:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/ansible-lint-junit", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/ansible_lint_junit/main.py", line 79, in main
    xml_nice = minidom.parseString(xml_string)
  File "/usr/lib64/python3.10/xml/dom/minidom.py", line 1998, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib64/python3.10/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib64/python3.10/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 2, column 264
```

**Comment by wasilak** [comment]
Hey @gtirloni, to be honest I can't reproduce your error. What params did you run ansible-lint with and which versions of ansible-lint and ansible-lint-junit are you using? 

I've installed all in docker in order to have clean, isolated setup and run following:
```bash
pip install ansible-lint
pip install ansible
pip install ansible-lint-junit
ansible-lint --nocolor --parseable test.yml | ansible-lint-junit
```
where content of `test.yml` is:
```yaml
- hosts: all
  tasks:
    - name: ensure templates dir is created
      file:
        path: "{{�| es_conf_dir�| }}/templates"
        state: directory
        owner: root
        group: "{{ es_group }}"
        mode: "2750"
```
stdout:
```bash
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: test.yml
WARNING  Listing 2 violation(s) that are fatal
You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - fqcn-builtins  # Use FQCN for builtin actions.
  - var-spacing  # Jinja2 variables and filters should have spaces before and after.

Finished with 2 failure(s), 0 warning(s) on 1 files.
```
and output xml junit file:
```xml
<?xml version="1.0" ?>
<testsuites>
	<testsuite errors="2" failures="0" tests="2" time="0">
		<testcase name="test.yml-1">
			<failure file="test.yml" line="3" message="fqcn-builtins: Use FQCN for builtin actions." type="Ansible Lint">fqcn-builtins: Use FQCN for builtin actions.</failure>
		</testcase>
		<testcase name="test.yml-2">
			<failure file="test.yml" line="3" message="var-spacing: Jinja2 variables and filters should have spaces before and after." type="Ansible Lint">var-spacing: Jinja2 variables and filters should have spaces before and after.</failure>
		</testcase>
	</testsuite>
</testsuites>
```
