### ISSUE TITLE
Version 0.9 can't install

### ISSUE THREAD

**Issue by ProFfeSsoRr** [wasilak/ansible-lint-junit#2]
```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from bootstrap import bootstrap
  File "/tmp/123/src/ansible-lint-junit-0.9/bootstrap/bootstrap.py", line 81
    print parsed_lines_xml
                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(parsed_lines_xml)?
```
Maybe mistype or something else?

**Comment by wasilak** [comment]
You are probably using Python 3, this lib was tested on Python 2. I need to upgrade it sometime ;)

**Comment by ProFfeSsoRr** [comment]
Yes, default python is 3 in my OS. Trying 2.7 now, thanks!

**Comment by wasilak** [comment]
I've updated version on PyPi, thanks for help! :)
