### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by ignatenkobrain** [wasilak/ansible-lint-junit#8]
```python
[brain@konsky-localdomain ci-infra]$ rm -rf .venv/
[brain@konsky-localdomain ci-infra]$ python3 -m venv .venv
[brain@konsky-localdomain ci-infra]$ source .venv/bin/activate
(.venv) [brain@konsky-localdomain ci-infra]$ pip install ansible ansible-lint ansible-lint-junit
Collecting ansible
  Downloading ansible-2.9.6.tar.gz (14.2 MB)
     |████████████████████████████████| 14.2 MB 9.2 MB/s 
Collecting ansible-lint
  Downloading ansible_lint-4.2.0-py2.py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 3.0 MB/s 
Collecting ansible-lint-junit
  Downloading ansible-lint-junit-0.14.tar.gz (2.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/brain/Projects/gooddata/ci-infra/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m6jg2kvr/ansible-lint-junit/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m6jg2kvr/ansible-lint-junit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-m6jg2kvr/ansible-lint-junit/pip-egg-info
         cwd: /tmp/pip-install-m6jg2kvr/ansible-lint-junit/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-m6jg2kvr/ansible-lint-junit/setup.py", line 3, in <module>
        from bootstrap import bootstrap
      File "/tmp/pip-install-m6jg2kvr/ansible-lint-junit/bootstrap/bootstrap.py", line 2, in <module>
        import lxml.etree as ET
    ModuleNotFoundError: No module named 'lxml'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(.venv) [brain@konsky-localdomain ci-infra]$ python --version
Python 3.8.2
```

**Comment by anhuong** [comment]
You have to run `pip install lxml` first. As you can see the error is that module doesn't exist.
